# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - travel-planner-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies (inside backend)
      - name: Install dependencies
        run: |
          cd backend
          npm install

      # Optional build step
      - name: Build app (if present)
        run: |
          cd backend
          npm run build --if-present

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_494EF3608DDF459F83B62772C92F5D8D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E2649882564542B0A8EFDB6CE121D946 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B241A06BD6764D5BAA65C3E85341AAB7 }}

      # Deploy ONLY backend folder
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'travel-planner-api'
          slot-name: 'Production'
          package: backend
